CREATE TABLE IF NOT EXISTS contact (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  `message` TEXT NOT NULL,
  PRIMARY KEY (`id`)
)
