CREATE TABLE IF NOT EXISTS users (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(32) NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  `firstname` VARCHAR(128) NOT NULL,
  `lastname` VARCHAR(128) NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  `token` VARCHAR(128) NOT NULL,
  UNIQUE(`username`),
  PRIMARY KEY (`id`)
)
